/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeekRouteImport } from './routes/week'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MonthRouteImport } from './routes/month'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthRoute = MonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/goals': typeof GoalsRoute
  '/month': typeof MonthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/goals': typeof GoalsRoute
  '/month': typeof MonthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/goals': typeof GoalsRoute
  '/month': typeof MonthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/goals'
    | '/month'
    | '/sitemap.xml'
    | '/week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/goals'
    | '/month'
    | '/sitemap.xml'
    | '/week'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/goals'
    | '/month'
    | '/sitemap.xml'
    | '/week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  GoalsRoute: typeof GoalsRoute
  MonthRoute: typeof MonthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeekRoute: typeof WeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/month': {
      id: '/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof MonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  GoalsRoute: GoalsRoute,
  MonthRoute: MonthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeekRoute: WeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
